## invoke with:
## alias csnake='snakemake -j 50 --cluster-config cluster.yaml --cluster "sbatch -J {rule} -p {cluster.p} --gres {cluster.gres} -n {cluster.n} -t {cluster.t} -c {cluster.c} --mem {cluster.mem}" '
## (that's now in bashrc. e.g. usage below)
## csnake train_flower_n2gt

from types import SimpleNamespace
from utils import flatten, recursive_map2

import files as F

localrules:
  flower_analysis_wild,
  flower_analysis_merge,

## flower data
rule all:
  input:
    [f"/projects/project-broaddus/denoise_experiments/cele/e01/nlm2_3d/t{count:03d}.tif" for count in range(120)],


rule nlmwild:
  output: "/projects/project-broaddus/denoise_experiments/cele/e01/nlm2_3d/t{count}.tif"
  run:
    import nlm_comparison
    print(wildcards.count)
    # nlm_comparison.nlm_3d_cele_just189()




rule flower_top:
  input: 
    F.all_tables.values(),
    F.flower_results,

rule flower_n2v2_wild:
  output: F.flowerdir + 'mask{n}_{m}/'
  run:
    import n2v2_flower, predict
    d = n2v2_flower.setup_flower_shutter(F.flowerdata,output[0])
    ta = n2v2_flower.train(d,end_epoch=600,mask_shape=range(int(wildcards.n)))
    predict.predict_on_full_2d_stack(F.flowerdata,output[0],output[0] + 'models/net600.pt')

rule flower_n2gt_wild:
  output: F.flowerdir + "n2gt2/{n}/"
  run:
    import n2gt_2d, predict
    d  = n2gt_2d.setup_flower_shutter(F.flowerdata, output[0])
    ta = n2gt_2d.init_training_artifacts()
    n2gt_2d.train(d,ta,end_epoch=600);
    predict.predict_on_full_2d_stack(F.flowerdata,output[0],output[0] + 'models/net600.pt')

rule flower_nlm:
  output: F.nlm_dir
  run:
    import nlm_comparison
    nlm_comparison.nlm_2d(F.flowerdata, output[0])

rule flower_bm3d:
  output: F.bm3d_dir
  run:
    import nlm_comparison
    nlm_comparison.bm3d_2d(F.flowerdata, output[0])

rule flower_analysis_wild:
  input:  F.flowerdir + '{dirname}/'
  output: F.flowerdir + '{dirname}/table.csv'
  run:
    import analysis2
    analysis2.load_prediction_and_eval_metrics__generic(input[0])

rule flower_analysis_merge:
  input: F.all_tables.values()
  output: F.flower_results #, F.flower_table_tex
  run:
    import analysis2
    analysis2.collect_data_scores_table()



localrules: shutter_analysis_wild

rule shuttertop:
  input:
    F.shutter_dir_nlm,
    F.shutter_dir_bm3d

rule shutter_analysis_wild:
  input:  F.shutterdir + '{dirname}/'
  output: F.shutterdir + '{dirname}/table.csv'
  run:
    import analysis2
    analysis2.load_prediction_and_eval_metrics__generic(input[0])

rule shutter_n2v2_single:
  output: F.shutterdir + 'mask{n}/'
  run:
    import n2v2_flower, predict
    # d = n2v2_flower.setup_flower_shutter(F.shutterdata,output[0])
    # ta = n2v2_flower.train(d,end_epoch=600,mask_shape=range(int(wildcards.n)))
    predict.predict_on_full_2d_stack(F.shutterdata,output[0],output[0] + 'models/net600.pt')

rule shutter_n2gt:
  output: F.shutterdir + "n2gt2/"
  run:
    import n2gt_2d, predict
    d  = n2gt_2d.setup_flower_shutter(F.shutterdata, output[0])
    ta = n2gt_2d.init_training_artifacts()
    n2gt_2d.train(d,ta,end_epoch=600);
    predict.predict_on_full_2d_stack(F.shutterdata,output[0],output[0] + 'models/net600.pt')

rule shutter_nlm:
  output: F.shutter_dir_nlm
  run:
    import nlm_comparison
    nlm_comparison.nlm_2d(F.shutterdata, output[0])

rule shutter_bm3d:
  output: F.shutter_dir_bm3d
  run:
    import nlm_comparison
    nlm_comparison.bm3d_2d(F.shutterdata, output[0])


# cele_home = '/lustre/projects/project-broaddus/denoise_experiments/cele/e01/'

# rule cele_n2v2_train_wild:
#   output: F.celedir + 'mask_1_x{n}y{m}/'
#   run:
#     import n2v2_cele
#     d  = n2v2_cele.setup(output[0])
#     ta = n2v2_cele.init_training_artifacts()
#     n2v2_cele.train(d, ta, end_epoch=100, xmask=range(int(wildcards.n)+1), ymask=range(int(wildcards.m)+1));
#     n2v2_cele.predict_movies(d)

rule cele_n2v2_pred_wild:
  input: F.cele.d_home + 'mask_1_x{n}y{m}/'
  output: F.cele.d_home + 'mask_1_x{n}y{m}/pimgs/'
  run:
    import n2v2_cele
    n2v2_cele.predict_from_new(input[0])

rule cele_nlm_wild:
  output: F.cele.d_home + 'nlm/{n}/'
  run:
    import nlm_comparison
    sigma = int(wildcards.n)/100
    nlm_comparison.nlm_3d_cele(output[0], sigma=sigma)





